[manager]
prepend_keymap = [
  { on = [
    "<C-s>",
  ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  { on = [
    "J",
  ], run = 'seek 1', desc = "Scrolling preview down" },
  { on = [
    "K",
  ], run = 'seek -1', desc = "Scrolling preview up" },
  { on = [
    "Q",
  ], run = 'quit', desc = "Quit" },
  { on = [
    "q",
    "q",
  ], run = 'quit', desc = "Quit" },
  { on = [
    "q",
    "t",
  ], run = 'close', desc = "Close Tab" },
  { on = [
    "g",
    ".",
  ], run = 'cd ~/.dotfiles/', desc = "Go to dotfiles" },
  { on = [
    "g",
    "y",
  ], run = 'cd ~/.config/yazi', desc = "Go to yazi" },
  { on = [
    "g",
    "n",
  ], run = 'cd ~/.config/nvim', desc = "Go to nvim" },
  { on = [
    "T",
  ], run = 'plugin hide-preview', desc = "Hide or show preview" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Go to the config directory" },
  { on = [
    "b",
    "a",
  ], run = 'plugin mactag --args="add"', desc = "Tag selected files" },
  { on = [
    "b",
    "r",
  ], run = 'plugin mactag --args="remove"', desc = "Untag selected files" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "Z", run = "plugin max-preview", desc = "Maximize or restore preview" },
  { on = "<C-g>", run = 'shell --block --confirm lazygit', desc = "Lazygit" },
  # { on = [],       run = "",     desc = "" },
]

[input]
prepend_keymap = [{ on = ["<Esc>"], run = "close", desc = "Cancel input" }]
