#!/usr/bin/env sh

# Y A B A I
# https://github.com/koekeishiya/yabai

# LOAD Scripting Additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# M o u s e
yabai -m config mouse_follows_focus          off          # set mouse follows focus mode
yabai -m config focus_follows_mouse          off          # set focus follows mouse mode
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# TILING
yabai -m config window_placement             second_child # windows become the right or bottom split when tiled
yabai -m config window_topmost               off          # floating windows are always on top
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# WINDOWS
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          8
yabai -m config active_window_border_color   0xffffff00
yabai -m config normal_window_border_color   0xff555555
yabai -m config window_shadow                on           # show shadows only for floating windows
yabai -m config window_opacity               off          # window opacity switch
yabai -m config window_gap                   16
yabai -m config insert_feedback_color        0xffd75f5f

# L A Y O U T
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16

# S P A C E
yabai -m config --space 4 layout               stack
yabai -m config --space 5 layout               float

yabai -m config external_bar all:36:0

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off # don't set above, conflict with Time Machine
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="^iTerm2$" sticky=on manage=off layer=above grid=200:30:1:118:28:80
yabai -m rule --add app="^Terminal$" sticky=on manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Tencent Lemon$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^IINA$" manage=off

yabai -m rule --add app="^Microsoft To Do$" space=3

coding='^(Android Studio|IntelliJ IDEA)$'
yabai -m rule --add app="${coding}" manage=off space=2

music='^(Spotify|NeteaseMusic|iTunes)$'
yabai -m rule --add app="${music}" space=4

chat='^(WeChat|Telegram)$'
yabai -m rule --add app="${chat}" space=3

killall limelight &> /dev/null
limelight &> /dev/null &

yabai -m signal --add event=window_created action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=space_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_resized action="sketchybar -m --trigger yabai_window_mode &> /dev/null"
yabai -m signal --add event=window_moved action="sketchybar -m --trigger yabai_window_mode &> /dev/null"

echo "yabai configuration loaded.."
