#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off          # set mouse follows focus mode
yabai -m config focus_follows_mouse          off          # set focus follows mouse mode
yabai -m config window_placement             second_child # windows become the right or bottom split when tiled
yabai -m config window_topmost               off          # floating windows are always on top
yabai -m config window_shadow                on           # show shadows only for floating windows
yabai -m config window_opacity               off          # window opacity switch
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xffffff00
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   8

# spacebar
# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar all:0:$SPACEBAR_HEIGHT
yabai -m config external_bar all:0:26

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="^iTerm2$" sticky=on manage=off layer=above grid=200:30:1:118:28:80 opacity=0.9
yabai -m rule --add app="^Terminal$" sticky=on manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off

yabai -m rule --add app="^Microsoft To Do$" space=2

music='^(Spotify|NeteaseMusic|iTunes)$'
yabai -m rule --add app="${music}" manage=off space=3

idea_title_regex="(.* \(/.*\))|^(Specify Inspection Scope|Choose Content to Paste|Preferences for New Projects|Welcome to Android Studio)$|^(Reformat File|Reformat Code|Preferences|Breakpoints|Rename).*"
yabai -m rule --add app="^Android Studio$" title="${idea_title_regex}" manage=off

killall limelight &> /dev/null
limelight &> /dev/null &

echo "yabai configuration loaded.."
