#!/usr/bin/env sh

spacebar -m config position           bottom
spacebar -m config height             26
spacebar -m config spacing_left       28
spacebar -m config spacing_right      36
spacebar -m config text_font          "JetBrainsMono Nerd Font Mono:Regular:18"
spacebar -m config icon_font          "JetBrainsMono Nerd Font Mono:Regular:20"
spacebar -m config background_color   0xBB202020
spacebar -m config foreground_color   0xBBC5D4DD
spacebar -m config space_icon_color   0xBB83AFE5
spacebar -m config power_icon_color   0xBBDADA93
spacebar -m config battery_icon_color 0xBBDADA93
spacebar -m config dnd_icon_color     0xBBa8a8a8
spacebar -m config clock_icon_color   0xBB83AFE5
spacebar -m config space_icon_strip   1 2 3 4 5 6 7 8 9
spacebar -m config power_icon_strip   🔋 ⚡
spacebar -m config space_icon         .
spacebar -m config dnd_icon           🌙
spacebar -m config clock_format       "📅 %Y-%m-%d  🕑 %R"
 
echo "spacebar configuration loaded.."
